services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: baawork_studio
      POSTGRES_USER: baawork
      POSTGRES_PASSWORD: baawork
    ports:
      - "55432:5432"
    volumes:
      - baawork_postgres:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  baawork_postgres:
